# echo calls Compose to run the command "echo 'Hello, World!'" in a Docker container
echo:
	echo custom validation check goes here

help:
	echo '@todo implement a self-documenting help - for now try `make echo` for our hello world demo'